### ISSUE TITLE
createCategoryCommand

### ISSUE THREAD

**Issue by tbarthel-fr** [SharUTC/SharUTC#3]
Bonjour,

J'ai une petite question concernant cette commande.

Pour l’exécuter, il suffit d'indiquer le nom de la nouvelle "Category".

Cependant, pour pouvoir l'afficher, il faut que l'ui puisse récupérer cette Category afin de la set en tant que model. 

Pour ce faire, la méthode prévue semble être 

```
mAppModel.getProfile().getCategories().findCategoryById() 
```

Je n'ai pas trouvé le PropertyChangeListener auquel il faut s'abonner pour être informé d'un changement au niveau des contacts et des catégories. 

Est ce qu'il en existe un que je n'aurais pas vu et qui fire l'id de la catégorie créée ?

**Comment by roal** [comment]
Yop,

Juste pour être sûr, ça été résolu ou pas ?
Parce que le ticket est fermé et t'as pas eu de réponse du coup ça me perturbe ^^

**Comment by mathildeAll** [comment]
Oui c'est OK. 
J'ai posé directement la question jeudi soir à Thomas ;).
