### ISSUE TITLE
Tests... en écrire c'est bien, penser à les lancer régulièrement c'est mieux !

### ISSUE THREAD

**Issue by gabz57** [SharUTC/SharUTC#4]
Certains disent que je râle, mais pour la 3ème ou 4ème fois déjà quelqu'un a pushé du code qui fait planter pas loin de 10 tests qui fonctionnaient très bien hier, lancez TOUS les tests avant de pusher s'il vous plait.

Je m'occupe de remettre de l'ordre dans tout ça en ce moment, évitez de faire trop de modifications pendant l'heure qui suit.

**Comment by AudreyBramy** [comment]
D'où vient le problème ?
Fait remonter les bug qu'on les corrige tous.

Audrey BRAMY

_Étudiante à l'Université de Technologie de Compiègne en Génie
Informatique *_ (Quatrième année)*
audrey.bramy@etu.utc.fr

2013/11/26 gabz57 notifications@github.com

**Comment by gabz57** [comment]
C'est déjà réglé. j'ai laissé la possibilité de stocker plusieurs messages dans les tests lors de l'envoi, il aurait fallu vérifier que les autres tests fonctionnent toujours, surtout avec ce type de changement.

**Comment by MikaYuoadas** [comment]
Désolé, c'est ma faute, j'ai push un peu vite à la fin de la scéance parceque j'étais pressé (j'avais un rdv après à PG).
Par contre c'est le dernier message qu'il fallait retourner (return messages.get(messages.size() - 1) plutôt que return messages.get(0) qui retourne le premier).

On en aura besoin pour des tests que laetitia avait commencé à écrire (certaines commandes font plusieurs fois appels à des méthodes send\* du réseau).

PS: essaie de faire des commits atomiques ("git add -p" FTW) parce que là y'a environ 200 lignes qui sont justes des suppressions/ajout de trailing-space/CRLF qu'on doit scroller pour seulement 2 lignes de changées concernant le bug à proprement parler.
